version: '3.2'
services:
  nginx0:
    image: 'nginx:alpine'
  nginx1:
    image: 'nginx:alpine'
  nginx2:
    image: 'nginx:alpine'

  l7:
    image: 'cirocosta/l7'
    volumes:
      - './config.yml:/etc/l7/config.yml'
    ports:
      - '80:80'
    command:
      - '--config=/etc/l7/config.yml'
